# ---
- name: create {{ minter_service_name }} directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ minter_user_gid }}"
    group: "{{ minter_user_group }}"
  with_items:
    - "{{ minter_dir }}"

# - name: copy {{nginx_service_name}} config
#   template:
#     src: "nginx.conf.j2"
#     dest: "{{nginx_config_dir}}/nginx.conf"
#
# - name: httppasswd configure
#   copy:
#     content: "{{nginx_auth_pass}}"
#     dest: "{{nginx_config_dir}}/httppasswd"
#     mode: 0644
#   when: nginx_with_password
#   notify: reload nginx
