---
- name: init node
  become: yes
  block:

    - name: config
      include: config.yml

    - name: service
      include: service.yml

  when: not flush_all | bool
  tags: install

- include: uninstall.yml
  become: yes
  when: flush_all | bool
  tags: uninstall
